#name: mainWorkflow
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: deploy
#        uses: appleboy/ssh-action@master
#        with:
#          username: "${{ secrets.SSH_USER }}"
#          host: "${{ secrets.SSH_HOST }}"
#          password: "${{ secrets.SSH_PASSWORD }}"
#          script: cd /var/www/dev.librarian.sk && ./server_deploy.sh
